# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  wcbalt-2017.dev:
    site_hosts:
      - canonical: wcbalt-2017.dev
        redirects:
          - www.wcbalt-2017.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: jimmy@smutek.net
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
